server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:mysql://localhost:3306/DBtour"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
<<<<<<< HEAD
  valid-duration: 500000 # in second
=======
  valid-duration: 15000 # in second
>>>>>>> d3fdc808e040ae78e1954bf50f62a626bcf5237c
  refreshable-duration: 36000 # in seconds
logging:
  level:
    com.example.auth_service.repository.httpclient.FileServiceClient: DEBUG
    feign: DEBUG
