server:
  port: 8086
  servlet:
    context-path: /tour

spring:
  application:
    name: tour-service
  datasource:
    url: "jdbc:mysql://localhost:3306/DBtour"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 15 # in second
  refreshable-duration: 36000 # in seconds
