server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/DBtour"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  return-url: http://localhost:3000/
  ipn-url: https://localhost:8080/api/momo/ipn-handler
  end-point: https://test-payment.momo.vn/v2/gateway/api
  request-type: captureWallet

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1800         # seconds (30 phút)
  refreshable-duration: 36000  # seconds (10 giờ)
