server:
  port: 8090
  servlet:
    context-path: /invoice

spring:
  application:
    name: invoice-service
  datasource:
    url: "jdbc:mysql://localhost:3306/DBtour"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true

#momo:
#  partner-code: MOMO
#  access-key: F8BBA842ECF85
#  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
#  return-url: http://localhost:3000/
#  ipn-url: https://localhost:8080/api/momo/ipn-handler
#  end-point: https://test-payment.momo.vn/v2/gateway/api
#  request-type: captureWallet

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in seconds
  refreshable-duration: 7200 # in seconds
logging:
  level:
    com.example.auth_service.repository.httpclient.FileServiceClient: DEBUG
    feign: DEBUG
